(()=>{'use strict';
  const params=new URLSearchParams(location.search);
  const pagePath=location.pathname.replace(/\/+$/,'');
  const customPcSelector='[data-service="Custom PC build"] a, a[href*="service=Custom%20PC%20build"], a[href*="service=Custom+PC+build"]';
  const routeCustomPcLinks=()=>document.querySelectorAll(customPcSelector).forEach(link=>{link.href='pc-build.html';if(link.classList.contains('card-link'))link.innerHTML='Plan my build <span>→</span>';});
  if((pagePath.endsWith('/request')||pagePath.endsWith('/request.html'))&&params.get('service')==='Custom PC build'){location.replace('pc-build.html');return;}
  routeCustomPcLinks();
  document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;const link=target?.closest(customPcSelector);if(!link)return;event.preventDefault();event.stopPropagation();location.assign('pc-build.html');},true);

  const footerCustomer=[...document.querySelectorAll('footer h3')].find(node=>node.textContent?.trim()==='Customers')?.parentElement;
  if(footerCustomer&&!footerCustomer.querySelector('a[href="privacy.html"]')){const link=document.createElement('a');link.href='privacy.html';link.textContent='Privacy Notice';footerCustomer.appendChild(link);}
  const footerAddress=document.querySelector('.footer-brand address');
  if(footerAddress&&!document.getElementById('store-hours')){const hours=document.createElement('div');hours.id='store-hours';hours.setAttribute('aria-label','Shop hours');hours.innerHTML='<div><span>Monday–Friday</span> <strong>10 AM–8 PM</strong></div><div><span>Saturday</span> <strong>10 AM–6 PM</strong></div><div><span>Sunday</span> <strong>Closed</strong></div>';footerAddress.insertAdjacentElement('afterend',hours);const directions=document.createElement('a');directions.href='https://www.google.com/maps/dir/?api=1&destination=700+North+Main+St+Ste+D+Blacksburg+VA+24060';directions.target='_blank';directions.rel='noopener';directions.textContent='Get directions →';hours.insertAdjacentElement('afterend',directions);}

  const client=window.supabaseClient;if(!client)return;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
  const storageKey='gc-public-chat-v1',maxSessionAge=30*24*60*60*1000;let session=null,pollTimer=null,startedAt=Date.now(),handoffPending=false;
  try{session=JSON.parse(localStorage.getItem(storageKey)||'null');if(session&&(!session.createdAt||Date.now()-Number(session.createdAt)>maxSessionAge)){localStorage.removeItem(storageKey);session=null;}}catch{session=null}
  const host=document.createElement('div');host.innerHTML=`<button class="gc-chat-launcher" type="button" aria-haspopup="dialog" aria-controls="gc-chat-panel" aria-expanded="false"><span>✦</span> Questions? Chat with us</button><section id="gc-chat-panel" class="gc-chat-panel" role="dialog" aria-modal="true" aria-label="Chat with GotCracked" hidden><header class="gc-chat-head"><div><strong>GotCracked chat</strong><small>Marlon handles quick questions; a team member can join when needed</small></div><button class="gc-chat-close" type="button" aria-label="Close chat">×</button></header><div class="gc-chat-body"><p class="gc-chat-welcome">Have a quick question? Send it here. For a repair intake or appointment, use the dedicated forms. Never send passwords or payment-card details. <a href="privacy.html">Privacy Notice</a>.</p><div class="gc-chat-messages"></div></div><form class="gc-chat-form"><input class="gc-chat-honeypot" name="companyWebsite" tabindex="-1" autocomplete="off"><label class="gc-chat-name">Your name<input name="name" maxlength="100" autocomplete="name" required></label><label class="gc-chat-email">Email for follow-up (optional)<input name="email" type="email" maxlength="160" autocomplete="email"></label><div class="gc-chat-contact" hidden><strong>Human follow-up</strong><p>Add a mobile number so the team can identify or create your customer record and follow up if this chat disconnects.</p><label>Mobile number<input name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="24" placeholder="(540) 555-1234"></label><label>Best way to follow up<select name="preferredContact"><option value="sms">Text / SMS</option><option value="call">Phone call</option></select></label></div><label>Your question<textarea name="message" maxlength="1600" required placeholder="How can we help?"></textarea></label><div class="gc-chat-actions"><button type="submit">Send message</button><button class="gc-chat-human" type="button">Talk to a person</button></div><p class="gc-chat-status" role="alert"></p></form></section>`;document.body.append(...host.childNodes);
  const panel=document.querySelector('.gc-chat-panel'),messages=document.querySelector('.gc-chat-messages'),form=document.querySelector('.gc-chat-form'),status=document.querySelector('.gc-chat-status'),contactCard=document.querySelector('.gc-chat-contact'),humanButton=document.querySelector('.gc-chat-human');
  const showContact=message=>{handoffPending=true;contactCard.hidden=false;form.elements.phone.required=true;humanButton.textContent=session?'Connect me to the team':'Start human handoff';if(message)status.textContent=message;setTimeout(()=>form.elements.phone?.focus(),40);};
  const hideContact=()=>{handoffPending=false;contactCard.hidden=true;form.elements.phone.required=false;humanButton.textContent='Talk to a person';};
  const render=items=>{messages.innerHTML=(items||[]).map(item=>`<div class="gc-chat-message ${item.sender==='customer'?'customer':'staff'}">${esc(item.body)}<small>${item.sender==='customer'?'You':item.sender==='system'?'Marlon Customer Care':'GotCracked team'}</small></div>`).join('');messages.parentElement.scrollTop=messages.parentElement.scrollHeight;};
  async function poll(){if(!session?.sessionId||document.hidden)return;try{const{data,error}=await client.functions.invoke('public-chat',{body:{action:'poll',sessionId:session.sessionId,token:session.token}});if(error||!data?.ok)throw error||new Error(data?.error);render(data.messages);}catch{}finally{clearTimeout(pollTimer);pollTimer=setTimeout(poll,4500)}}
  const launcher=document.querySelector('.gc-chat-launcher');let lastFocus=null;
  function open(){lastFocus=document.activeElement;panel.hidden=false;panel.classList.add('open');launcher.hidden=true;launcher.setAttribute('aria-expanded','true');startedAt=Date.now();if(session){document.querySelector('.gc-chat-name').hidden=true;document.querySelector('.gc-chat-email').hidden=true;poll();}setTimeout(()=>form.elements.message.focus(),50)}
  function close(){panel.classList.remove('open');panel.hidden=true;launcher.hidden=false;launcher.setAttribute('aria-expanded','false');clearTimeout(pollTimer);(lastFocus||launcher)?.focus()}
  launcher.addEventListener('click',open);document.querySelector('.gc-chat-close').addEventListener('click',close);document.querySelectorAll('[data-chat-open]').forEach(button=>button.addEventListener('click',open));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&panel.classList.contains('open'))close();});
  humanButton?.addEventListener('click',async()=>{
    if(!handoffPending){showContact('Add your mobile number, then connect to the GotCracked team.');if(!form.elements.message.value.trim())form.elements.message.value='I would like to talk to a person.';return;}
    if(!session){form.requestSubmit();return;}
    const phone=String(form.elements.phone.value||'').trim();
    const email=String(form.elements.email.value||'').trim();
    const preferredContact=String(form.elements.preferredContact.value||'sms');
    if(!phone){status.textContent='Enter a mobile number so the team can follow up.';form.elements.phone.focus();return;}
    humanButton.disabled=true;status.textContent='Connecting you to the team…';
    try{
      const{data,error}=await client.functions.invoke('public-chat',{body:{action:'handoff',sessionId:session.sessionId,token:session.token,phone,email,preferredContact,reason:'customer_requested_human'}});
      if(error||!data?.ok)throw new Error(data?.error||error?.message||'Unable to connect you.');
      hideContact();status.textContent='A GotCracked team member can now join this conversation.';poll();
    }catch(error){status.textContent=error.message||'Unable to connect you.'}
    finally{humanButton.disabled=false}
  });
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;status.textContent='';try{const fields=Object.fromEntries(new FormData(form));const body=session?{action:'send',sessionId:session.sessionId,token:session.token,message:fields.message}:{action:'start',...fields,requestHuman:handoffPending,formStartedAt:startedAt};const{data,error}=await client.functions.invoke('public-chat',{body});if(error||!data?.ok)throw new Error(data?.error||error?.message||'Unable to send.');if(data.sessionId){session={sessionId:data.sessionId,token:data.token,createdAt:Date.now()};localStorage.setItem(storageKey,JSON.stringify(session));document.querySelector('.gc-chat-name').hidden=true;}form.elements.message.value='';render(data.messages);if(data.handoffReady){hideContact();status.textContent='A GotCracked team member can now join this conversation.';}else if(data.requiresContact){showContact('Marlon needs your mobile number before handing this conversation to the team.');}poll();}catch(error){status.textContent=error.message||'Unable to send.'}finally{button.disabled=false}});
})();

