(()=>{'use strict';
  const client=window.supabaseClient;if(!client)return;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
  const storageKey='gc-public-chat-v1';let session=null,pollTimer=null,startedAt=Date.now();
  try{session=JSON.parse(localStorage.getItem(storageKey)||'null')}catch{session=null}
  const host=document.createElement('div');host.innerHTML=`<button class="gc-chat-launcher" type="button" aria-haspopup="dialog"><span>✦</span> Questions? Chat with us</button><section class="gc-chat-panel" role="dialog" aria-label="Chat with GotCracked"><header class="gc-chat-head"><div><strong>GotCracked chat</strong><small>Replies come from our team through Discord</small></div><button class="gc-chat-close" type="button" aria-label="Close chat">×</button></header><div class="gc-chat-body"><p class="gc-chat-welcome">Have a quick question? Send it here. For a repair intake or appointment, use the dedicated forms.</p><div class="gc-chat-messages"></div></div><form class="gc-chat-form"><input class="gc-chat-honeypot" name="companyWebsite" tabindex="-1" autocomplete="off"><label class="gc-chat-name">Your name<input name="name" maxlength="100" autocomplete="name" required></label><label class="gc-chat-email">Email for follow-up (optional)<input name="email" type="email" maxlength="160" autocomplete="email"></label><label>Your question<textarea name="message" maxlength="1600" required placeholder="How can we help?"></textarea></label><button type="submit">Send message</button><p class="gc-chat-status" role="alert"></p></form></section>`;document.body.append(...host.childNodes);
  const panel=document.querySelector('.gc-chat-panel'),messages=document.querySelector('.gc-chat-messages'),form=document.querySelector('.gc-chat-form'),status=document.querySelector('.gc-chat-status');
  const render=items=>{messages.innerHTML=(items||[]).map(item=>`<div class="gc-chat-message ${item.sender==='customer'?'customer':'staff'}">${esc(item.body)}<small>${item.sender==='customer'?'You':'GotCracked team'}</small></div>`).join('');messages.parentElement.scrollTop=messages.parentElement.scrollHeight;};
  async function poll(){if(!session?.sessionId||document.hidden)return;try{const{data,error}=await client.functions.invoke('public-chat',{body:{action:'poll',...session}});if(error||!data?.ok)throw error||new Error(data?.error);render(data.messages);}catch{}finally{clearTimeout(pollTimer);pollTimer=setTimeout(poll,4500)}}
  function open(){panel.classList.add('open');document.querySelector('.gc-chat-launcher').hidden=true;startedAt=Date.now();if(session){document.querySelector('.gc-chat-name').hidden=true;document.querySelector('.gc-chat-email').hidden=true;poll();}setTimeout(()=>form.elements.message.focus(),50)}
  function close(){panel.classList.remove('open');document.querySelector('.gc-chat-launcher').hidden=false;clearTimeout(pollTimer)}
  document.querySelector('.gc-chat-launcher').addEventListener('click',open);document.querySelector('.gc-chat-close').addEventListener('click',close);document.querySelectorAll('[data-chat-open]').forEach(button=>button.addEventListener('click',open));
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;status.textContent='';try{const fields=Object.fromEntries(new FormData(form));const body=session?{action:'send',...session,message:fields.message}:{action:'start',...fields,formStartedAt:startedAt};const{data,error}=await client.functions.invoke('public-chat',{body});if(error||!data?.ok)throw new Error(data?.error||error?.message||'Unable to send.');if(data.sessionId){session={sessionId:data.sessionId,token:data.token};localStorage.setItem(storageKey,JSON.stringify(session));document.querySelector('.gc-chat-name').hidden=true;document.querySelector('.gc-chat-email').hidden=true;}form.elements.message.value='';render(data.messages);poll();}catch(error){status.textContent=error.message||'Unable to send.'}finally{button.disabled=false}});
})();
