(()=>{'use strict';
  const params=new URLSearchParams(location.search);
  const pagePath=location.pathname.replace(/\/+$/,'');
  const customPcSelector='[data-service="Custom PC build"] a, a[href*="service=Custom%20PC%20build"], a[href*="service=Custom+PC+build"]';
  const routeCustomPcLinks=()=>document.querySelectorAll(customPcSelector).forEach(link=>{link.href='pc-build.html';if(link.classList.contains('card-link'))link.innerHTML='Plan my build <span>→</span>';});
  if((pagePath.endsWith('/request')||pagePath.endsWith('/request.html'))&&params.get('service')==='Custom PC build'){location.replace('pc-build.html');return;}
  routeCustomPcLinks();
  document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;const link=target?.closest(customPcSelector);if(!link)return;event.preventDefault();event.stopPropagation();location.assign('pc-build.html');},true);

  const footerCustomer=[...document.querySelectorAll('footer h3')].find(node=>node.textContent?.trim()==='Customers')?.parentElement;
  if(footerCustomer&&!footerCustomer.querySelector('a[href="privacy.html"]')){const link=document.createElement('a');link.href='privacy.html';link.textContent='Privacy Notice';footerCustomer.appendChild(link);}
  const footerAddress=document.querySelector('.footer-brand address');
  if(footerAddress&&!document.getElementById('store-hours')){const hours=document.createElement('div');hours.id='store-hours';hours.setAttribute('aria-label','Shop hours');hours.innerHTML='<div><span>Monday–Friday</span> <strong>9 AM–6 PM</strong></div><div><span>Saturday</span> <strong>10 AM–4 PM</strong></div><div><span>Sunday</span> <strong>Closed</strong></div>';footerAddress.insertAdjacentElement('afterend',hours);const directions=document.createElement('a');directions.href='https://www.google.com/maps/dir/?api=1&destination=700+North+Main+St+Ste+D+Blacksburg+VA+24060';directions.target='_blank';directions.rel='noopener';directions.textContent='Get directions →';hours.insertAdjacentElement('afterend',directions);}

  const client=window.supabaseClient;if(!client)return;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
  const storageKey='gc-public-chat-v1',maxSessionAge=30*24*60*60*1000;let session=null,pollTimer=null,startedAt=Date.now();
  try{session=JSON.parse(localStorage.getItem(storageKey)||'null');if(session&&(!session.createdAt||Date.now()-Number(session.createdAt)>maxSessionAge)){localStorage.removeItem(storageKey);session=null;}}catch{session=null}
  const host=document.createElement('div');host.innerHTML=`<button class="gc-chat-launcher" type="button" aria-haspopup="dialog"><span>✦</span> Questions? Chat with us</button><section class="gc-chat-panel" role="dialog" aria-label="Chat with GotCracked"><header class="gc-chat-head"><div><strong>GotCracked chat</strong><small>Marlon handles quick questions; a team member can join when needed</small></div><button class="gc-chat-close" type="button" aria-label="Close chat">×</button></header><div class="gc-chat-body"><p class="gc-chat-welcome">Have a quick question? Send it here. For a repair intake or appointment, use the dedicated forms. Never send passwords or payment-card details. <a href="privacy.html">Privacy Notice</a>.</p><div class="gc-chat-messages"></div></div><form class="gc-chat-form"><input class="gc-chat-honeypot" name="companyWebsite" tabindex="-1" autocomplete="off"><label class="gc-chat-name">Your name<input name="name" maxlength="100" autocomplete="name" required></label><label class="gc-chat-email">Email for follow-up (optional)<input name="email" type="email" maxlength="160" autocomplete="email"></label><label>Your question<textarea name="message" maxlength="1600" required placeholder="How can we help?"></textarea></label><div class="gc-chat-actions"><button type="submit">Send message</button><button class="gc-chat-human" type="button">Talk to a person</button></div><p class="gc-chat-status" role="alert"></p></form></section>`;document.body.append(...host.childNodes);
  const panel=document.querySelector('.gc-chat-panel'),messages=document.querySelector('.gc-chat-messages'),form=document.querySelector('.gc-chat-form'),status=document.querySelector('.gc-chat-status');
  const render=items=>{messages.innerHTML=(items||[]).map(item=>`<div class="gc-chat-message ${item.sender==='customer'?'customer':'staff'}">${esc(item.body)}<small>${item.sender==='customer'?'You':item.sender==='system'?'Marlon Customer Care':'GotCracked team'}</small></div>`).join('');messages.parentElement.scrollTop=messages.parentElement.scrollHeight;};
  async function poll(){if(!session?.sessionId||document.hidden)return;try{const{data,error}=await client.functions.invoke('public-chat',{body:{action:'poll',sessionId:session.sessionId,token:session.token}});if(error||!data?.ok)throw error||new Error(data?.error);render(data.messages);}catch{}finally{clearTimeout(pollTimer);pollTimer=setTimeout(poll,4500)}}
  function open(){panel.classList.add('open');document.querySelector('.gc-chat-launcher').hidden=true;startedAt=Date.now();if(session){document.querySelector('.gc-chat-name').hidden=true;document.querySelector('.gc-chat-email').hidden=true;poll();}setTimeout(()=>form.elements.message.focus(),50)}
  function close(){panel.classList.remove('open');document.querySelector('.gc-chat-launcher').hidden=false;clearTimeout(pollTimer)}
  document.querySelector('.gc-chat-launcher').addEventListener('click',open);document.querySelector('.gc-chat-close').addEventListener('click',close);document.querySelectorAll('[data-chat-open]').forEach(button=>button.addEventListener('click',open));
  document.querySelector('.gc-chat-human')?.addEventListener('click',()=>{form.elements.message.value="I would like to talk to a person.";form.requestSubmit();});
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;status.textContent='';try{const fields=Object.fromEntries(new FormData(form));const body=session?{action:'send',sessionId:session.sessionId,token:session.token,message:fields.message}:{action:'start',...fields,formStartedAt:startedAt};const{data,error}=await client.functions.invoke('public-chat',{body});if(error||!data?.ok)throw new Error(data?.error||error?.message||'Unable to send.');if(data.sessionId){session={sessionId:data.sessionId,token:data.token,createdAt:Date.now()};localStorage.setItem(storageKey,JSON.stringify(session));document.querySelector('.gc-chat-name').hidden=true;document.querySelector('.gc-chat-email').hidden=true;}form.elements.message.value='';render(data.messages);poll();}catch(error){status.textContent=error.message||'Unable to send.'}finally{button.disabled=false}});
})();
