(()=>{'use strict';
  const form=document.getElementById('pc-build-form');if(!form)return;
  const steps=[...form.querySelectorAll('.pc-step')],progress=[...form.querySelectorAll('.pc-progress span')];
  const research=document.getElementById('pc-research'),result=document.getElementById('pc-result'),error=document.getElementById('pc-build-error');
  const gamingFields=document.querySelector('.pc-gaming-fields');let current=0,statusTimer=null;
  const money=cents=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((Number(cents)||0)/100);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  form.elements.formStartedAt.value=String(Date.now());

  function show(index){current=Math.max(0,Math.min(steps.length-1,index));steps.forEach((step,i)=>step.classList.toggle('active',i===current));progress.forEach((bar,i)=>bar.classList.toggle('active',i<=current));error.textContent='';steps[current]?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
  function visibleRequired(step){return [...step.querySelectorAll('[required]')].filter(field=>!field.closest('[hidden]'));}
  function validate(){let ok=true;for(const field of visibleRequired(steps[current])){if(!field.checkValidity()){field.classList.add('invalid');if(ok)field.focus();ok=false}else field.classList.remove('invalid')}if(!ok)error.textContent='Complete the required fields before continuing.';return ok;}
  function updateGaming(){const included=form.elements.gamingIncluded?.value==='yes';if(gamingFields)gamingFields.hidden=!included;for(const name of ['games','resolution','targetFps','imageQuality']){const field=form.elements[name];if(field)field.required=included;}}
  form.addEventListener('change',event=>{if(event.target.name==='gamingIncluded')updateGaming();});updateGaming();
  form.querySelectorAll('[data-next]').forEach(button=>button.addEventListener('click',()=>{if(validate())show(current+1)}));
  form.querySelectorAll('[data-back]').forEach(button=>button.addEventListener('click',()=>show(current-1)));

  const statuses=['Reading your goals and budget…','Researching current component availability…','Comparing current US retailer pricing…','Running the proposed parts through Newegg PC Builder compatibility checks…','Cross-checking manufacturer sockets, dimensions, connectors, cooling, and BIOS support…','Checking PSU headroom against Newegg’s wattage estimate…','Balancing performance, thermals, noise, and upgrade path…','Preparing your build estimate…'];
  function startResearch(){form.hidden=true;result.classList.remove('active');research.classList.add('active');let i=0;const node=document.querySelector('.pc-research-status');if(node)node.textContent=statuses[0];statusTimer=setInterval(()=>{i=Math.min(i+1,statuses.length-1);if(node)node.textContent=statuses[i]},2600);}
  function stopResearch(){clearInterval(statusTimer);research.classList.remove('active');}
  function renderEstimated(data){const rec=data.recommendation||{};result.innerHTML=`<div class="pc-result-head"><div><p class="eyebrow"><span></span>Your GotCracked build</p><h2>${esc(rec.buildName||'Recommended custom PC')}</h2><p class="pc-result-summary">${esc(rec.summary||'A build matched to the goals you shared.')}</p></div><div class="pc-total"><small>Estimated build total</small><strong>${money(data.estimatedTotalCents)}</strong><small>Parts + GotCracked build service</small></div></div><div class="pc-note" style="margin:18px 0"><strong>✓ Compatibility verified before pricing</strong><p>${esc(data.compatibilityMethod||rec.compatibilityMethod||'Newegg PC Builder compatibility filtering + manufacturer specifications.')}</p></div><div class="pc-parts">${(rec.parts||[]).map(part=>`<article class="pc-part"><small>${esc(part.category)}</small><strong>${esc(part.name)}</strong><p>${esc(part.rationale||'Selected for this build.')}</p></article>`).join('')}</div><div class="pc-result-notes"><article class="pc-note"><strong>Expected experience</strong><p>${esc(rec.performance||'')}</p></article><article class="pc-note"><strong>Upgrade path</strong><p>${esc(rec.upgradePath||'')}</p></article><article class="pc-note"><strong>Compatibility</strong><p>${esc(rec.compatibility||'')}</p></article><article class="pc-note"><strong>Budget fit</strong><p>${esc(rec.budgetNote||'')}</p></article></div><div class="pc-market-notice"><strong>RAM market notice</strong>${esc(data.ramMarketNotice||'Memory pricing is unusually volatile right now. This estimate uses current market pricing and may change.')}<small>Industry outlooks are forecasts, not guarantees of future retail prices.</small></div><p class="pc-estimate-meta">Request <span class="pc-reference">${esc(data.reference)}</span> · Estimate valid through ${data.estimateValidUntil?new Date(data.estimateValidUntil).toLocaleDateString():'the date shown by GotCracked'}. Component availability and retailer prices can change before parts are ordered. Taxes, optional peripherals, shipping, or requested changes may affect the final approved quote.</p><div class="pc-nav"><a class="button button-ghost" href="index.html">Back to website</a><button class="button" type="button" data-start-over>Start another build →</button></div>`;result.classList.add('active');result.querySelector('[data-start-over]')?.addEventListener('click',reset);}
  function renderManual(data){result.innerHTML=`<div class="pc-manual"><p class="eyebrow"><span></span>Build request received</p><h2>Compatibility needs a human review.</h2><p>${esc(data.message||'Your survey is saved. GotCracked will review the exact parts through Newegg PC Builder and manufacturer specifications before showing you a price.')}</p><p><strong>No automated estimate was released.</strong> We would rather review the configuration than show you a price based on an unverified parts combination.</p><p>Reference: <span class="pc-reference">${esc(data.reference)}</span></p></div><div class="pc-market-notice"><strong>RAM market notice</strong>Memory prices are unusually high as AI/data-center demand and HBM production consume more global DRAM manufacturing capacity. Industry forecasts expect supply to remain constrained through 2027, with more meaningful relief potentially arriving in late 2027 into 2028 as new capacity ramps.<small>That timing is an industry outlook, not a guarantee of future retail pricing.</small></div><div class="pc-nav"><a class="button button-ghost" href="index.html">Back to website</a><button class="button" type="button" data-start-over>Start another build →</button></div>`;result.classList.add('active');result.querySelector('[data-start-over]')?.addEventListener('click',reset);}
  function renderResearchUnavailable(data){result.innerHTML=`<div class="pc-manual"><p class="eyebrow"><span></span>Build request saved</p><h2>Research is temporarily unavailable.</h2><p>${esc(data.message||'Your survey is safely stored. GotCracked will retry the research or contact you.')}</p><p><strong>This is not a compatibility failure.</strong> No automated estimate was released because the research service did not complete.</p><p>Reference: <span class="pc-reference">${esc(data.reference)}</span></p></div><div class="pc-nav"><a class="button button-ghost" href="index.html">Back to website</a><button class="button" type="button" data-start-over>Start another build →</button></div>`;result.classList.add('active');result.querySelector('[data-start-over]')?.addEventListener('click',reset);}
  function reset(){result.classList.remove('active');form.reset();form.hidden=false;form.elements.formStartedAt.value=String(Date.now());updateGaming();show(0);scrollTo({top:0,behavior:'smooth'});}

  form.addEventListener('submit',async event=>{event.preventDefault();if(!validate())return;const submit=form.querySelector('[type="submit"]');submit.disabled=true;error.textContent='';startResearch();try{if(!window.supabaseClient?.functions)throw new Error('The build research service is temporarily unavailable.');const payload=Object.fromEntries(new FormData(form));const {data,error:fnError}=await window.supabaseClient.functions.invoke('custom-pc-build',{body:payload});if(fnError||!data?.ok)throw new Error(data?.error||fnError?.message||'Unable to research the build.');stopResearch();if(data.status==='estimated')renderEstimated(data);else if(data.status==='research_unavailable')renderResearchUnavailable(data);else renderManual(data);result.scrollIntoView({behavior:'smooth',block:'start'});}catch(err){stopResearch();form.hidden=false;error.textContent=err?.message||'Unable to prepare the build right now. Please contact GotCracked.';steps[current]?.scrollIntoView({behavior:'smooth',block:'start'});}finally{submit.disabled=false;}});
})();

